language: python
python:
- 3.6
before_install:
  - sudo apt-get install -y doxygen
install:
- pip install -r requirements.txt
script:
- mkdocs build --verbose --clean
deploy:
  provider: pages
  target-branch: master
  local-dir: site
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: source
