site_name: 'CP3-llbb Analysis Tools'
site_description: 'Documentation for the CP3-llbb Analysis Tools'
site_author: 'IRMP/CP3, Université catholique de Louvain'
site_url: 'https://cp3-llbb.github.io/'
repo_name: 'cp3-llbb/cp3-llbb.github.io'
repo_url: 'https://github.com/cp3-llbb/cp3-llbb.github.io'
copyright: 'Copyright &copy; 2018 IRMP/CP3, Université catholique de Louvain'

nav:
  - Introduction: index.md
  - Framework:
    - Overview: framework.md
    - Jenkins CI: fwk_jenkins.md
    - Doxygen: doxyfwk/index.html
  - GridIn: gridin.md
  - plotIt: plotit.md
  - Bamboo: bamboo.md

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.emoji

plugins:
  - markdownextradata
  - search
  #  - git-revision-date-localized:
  #  enable_creation_date: true
  - doxygen:
      tryclone: true
      packages:
        - doxyfwk:
            url    : https://github.com/cp3-llbb/Framework.git
            config : docs/doxygen.cfg

# https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
theme:
  name: 'material'
  language: 'en'
  palette:
    - scheme: slate
      primary: 'indigo'
      accent: 'indigo' 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - header.autohide
    - navigation.footer
    - content.action.edit
    - content.action.view
    - content.code.copy
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/cp3-llbb
  framework:
    cmsswrelease: CMSSW_8_0_30
    defaultbranch: CMSSW_8_0_6p

# Google Analytics
# google_analytics:
#   - 'UA-XXXXXXXX-X'
#   - 'auto'
