name: CI

on:
  push:
    branches: [ source ]
  pull_request:
    branches: [ source ]

  workflow_dispatch:

jobs:
  build:
    name: Deply mkdoc site
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get install -y doxygen
          pip install -r "${GITHUB_WORKSPACE}/requirements.txt"
      - name: Build site
        run: mkdocs build --verbose --clean
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        if: github.ref == 'refs/heads/source'
        with:
          branch: master
          folder: site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
